### ISSUE TITLE
Failed to resolve: com.github.aykuttasil:CallRecorder:1.2.8

### ISSUE THREAD

**Issue by anonym24** [aykuttasil/CallRecorder#22]
Failed to resolve: com.github.aykuttasil:CallRecorder:1.2.8

`implementation 'com.github.aykuttasil:CallRecorder:1.2.8'`

```
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
```

**Comment by aykuttasil** [comment]
implementation 'com.github.aykuttasil:CallRecorder:1.2.9' @anonym24

**Comment by xpmkm89** [comment]
still showing faild to resolve implementation 'com.github.aykuttasil:CallRecorder:1.2.9

**Comment by aykuttasil** [comment]
Please make you sure added follow code blocks.

repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' } 
    }

and 

implementation 'com.github.aykuttasil:CallRecorder:1.5.0'

@xpmkm89

**Comment by maheshutm** [comment]
still showing faild to resolve implementation 'com.github.aykuttasil:CallRecorder:1.5.0
