### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [aykuttasil/CallRecorder#29]
Hi @aykuttasil . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by aykuttasil** [comment]
Ok. 
I am happy for this.
Is there anything you want from me? @mirzazulfan

**Comment by mirzazulfan** [comment]
Thanks for your response. I'll do my best and shown it to you.

**Comment by mirzazulfan** [comment]
Hi @aykuttasil .. I've designed a logo. What do you think? if you need to change, please let me know.
![call](https://user-images.githubusercontent.com/36124339/46198545-ed331b80-c336-11e8-81a5-96d6eb13bc66.png)

**Comment by aykuttasil** [comment]
Oh, super! Thank you.
I think it's very nice on the left. @mirzazulfan

**Comment by mirzazulfan** [comment]
Thanks :) @aykuttasil i'll send you files and pr.
