### ISSUE TITLE
VOIP calls Whatsapp/Facebook not recording

### ISSUE THREAD

**Issue by Zulqurnain** [aykuttasil/CallRecorder#43]
it's a feature request or suggestion for me, how can we use this library to record VOIP calls like facebook/WhatsApp?
 
You haven't provided it yet in this lib, but can you suggest me how can i achieve this using this lib or without?

**Comment by vickyleu** [comment]
try [Tor-ScreenRec](https://github.com/Tornaco/Tor-ScreenRec)

**Comment by aalmangour** [comment]
So this is not happening anytime soon?
